// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fKyvXDikpqMi2QhqwcE53Cl5x2HBQgQ',
    appId: '1:934690767978:web:73cdff732c39670276b613',
    messagingSenderId: '934690767978',
    projectId: 'swiminit05',
    authDomain: 'swiminit05.firebaseapp.com',
    storageBucket: 'swiminit05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_S7gpWnzR8RQmzzzndg1ocZGq5RYce9M',
    appId: '1:934690767978:android:0738fc69e8c9eb3176b613',
    messagingSenderId: '934690767978',
    projectId: 'swiminit05',
    storageBucket: 'swiminit05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ZKyE51tsIoHvtGgz0dsBO2dPKj_b2NM',
    appId: '1:934690767978:ios:1ead32f28c66cf9976b613',
    messagingSenderId: '934690767978',
    projectId: 'swiminit05',
    storageBucket: 'swiminit05.appspot.com',
    iosClientId: '934690767978-2ogr40sn2hisgm2foomjnppo387qod09.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiminit05',
  );
}
